---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
  labels:
    app: shopfront
spec:
  type: NodePort
  selector:
    app: shopfront
  ports:
  - protocol: TCP
    port: 8010         # Service port
    targetPort: 8010   # Container port in the pod
    nodePort: 32458    # Node port (optional, specify only if you want a fixed external port)
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
spec:
  selector:
    matchLabels:
      app: shopfront
  replicas: 1
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: shopfront
        image: sunil729/shopfront:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
      # Optional: Specify imagePullSecrets if the Docker image is private
      imagePullSecrets:
        - name: my-docker-secret  # Replace with the name of your Kubernetes secret for Docker credentials if needed
